### ISSUE TITLE
hello there, i wanna ask where can i get the data for training, it seems that you have not uploaded the data in these files and besides, the data_preprocessing.py is missing i guess? 

### ISSUE THREAD

**Issue by SinnKazaf** [ma-compbio/UNADON#1]

**Comment by muyuyang** [comment]
Hello, thank you for reaching out! To obtain the DNA sequence data, please download the human genome assembly hg38. For the epigenomic features, I suggest accessing the ENCODE (https://www.encodeproject.org/) and 4DN (https://data.4dnucleome.org/) data portals. You can find the specific data accession numbers in the supplementary table 1 of the paper, which you can use to locate and download the datasets. Regarding TSA-seq signals, please note that currently, only the SON TSA-seq data is publicly available. You can find and download this data from the 4DN data portal.
